import path from "node:path";
import { fileURLToPath } from "node:url";
import HtmlWebpackPlugin from "html-webpack-plugin";
import CopyWebpackPlugin from "copy-webpack-plugin";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

export default {
  entry: {
    main: "./src/index.js",
    about: "./src/about.js",
    contact: "./src/contact.js",
    blog: "./src/blog.js",
    "blog-static-vs-cms": "./src/blog-static-vs-cms.js",
    "blog-aio-seo": "./src/blog-aio-seo.js",
    "blog-core-web-vitals": "./src/blog-core-web-vitals.js",
    "blog-google-business-profile": "./src/blog-google-business-profile.js",
    "blog-line-oa-website": "./src/blog-line-oa-website.js",
    "blog-responsive-design": "./src/blog-responsive-design.js",
    "blog-website-cost": "./src/blog-website-cost.js",
    "blog-shopify-vs-custom": "./src/blog-shopify-vs-custom.js",
    "blog-page-speed": "./src/blog-page-speed.js",
    "blog-landing-page": "./src/blog-landing-page.js",
    "blog-ssl-https": "./src/blog-ssl-https.js",
    "blog-domain-hosting": "./src/blog-domain-hosting.js",
    "blog-restaurant-website": "./src/blog-restaurant-website.js",
    "blog-web-app-vs-mobile-app": "./src/blog-web-app-vs-mobile-app.js",
    "blog-google-ads-website": "./src/blog-google-ads-website.js",
    "blog-online-booking": "./src/blog-online-booking.js",
    "blog-website-analytics": "./src/blog-website-analytics.js",
    "blog-website-copywriting": "./src/blog-website-copywriting.js",
    "blog-clinic-website": "./src/blog-clinic-website.js",
    "blog-thai-ecommerce-tips": "./src/blog-thai-ecommerce-tips.js",
    "blog-pdpa-website": "./src/blog-pdpa-website.js",
    "blog-website-maintenance": "./src/blog-website-maintenance.js",
    "portfolio-luxe-watch": "./src/portfolio-luxe-watch.js",
    "portfolio-cafe":      "./src/portfolio-cafe.js",
    "portfolio-puphub":    "./src/portfolio-puphub.js",
    "portfolio-glostar":   "./src/portfolio-glostar.js",
    "portfolio-photographer": "./src/portfolio-photographer.js",
  },
  output: {
    filename: "[name].js",
    path: path.resolve(__dirname, "dist"),
    assetModuleFilename: (pathData) => pathData.filename.replace(/^src\//, ""),
    clean: true,
  },
  module: {
    rules: [
      {
        test: /\.html$/i,
        loader: "html-loader",
        options: {
          sources: false,
        },
      },
      {
        test: /\.(png|svg|jpg|jpeg|gif|webp)$/i,
        type: "asset/resource",
      },
      {
        test: /\.(woff|woff2|eot|ttf|otf)$/i,
        type: "asset/resource",
      },
    ],
  },
  plugins: [
    new HtmlWebpackPlugin({
      template: "./src/index.html",
      filename: "index.html",
      chunks: ["main"],
      scriptLoading: "defer",
    }),
    new HtmlWebpackPlugin({
      template: "./src/about.html",
      filename: "about.html",
      chunks: ["about"],
      scriptLoading: "defer",
    }),
    new HtmlWebpackPlugin({
      template: "./src/contact.html",
      filename: "contact.html",
      chunks: ["contact"],
      scriptLoading: "defer",
    }),
    new HtmlWebpackPlugin({
      template: "./src/blog.html",
      filename: "blog.html",
      chunks: ["blog"],
      scriptLoading: "defer",
    }),
    new HtmlWebpackPlugin({
      template: "./src/blog-static-vs-cms.html",
      filename: "blog-static-vs-cms.html",
      chunks: ["blog-static-vs-cms"],
      scriptLoading: "defer",
    }),
    new HtmlWebpackPlugin({
      template: "./src/blog-aio-seo.html",
      filename: "blog-aio-seo.html",
      chunks: ["blog-aio-seo"],
      scriptLoading: "defer",
    }),
    new HtmlWebpackPlugin({
      template: "./src/blog-core-web-vitals.html",
      filename: "blog-core-web-vitals.html",
      chunks: ["blog-core-web-vitals"],
      scriptLoading: "defer",
    }),
    new HtmlWebpackPlugin({
      template: "./src/blog-google-business-profile.html",
      filename: "blog-google-business-profile.html",
      chunks: ["blog-google-business-profile"],
      scriptLoading: "defer",
    }),
    new HtmlWebpackPlugin({
      template: "./src/blog-line-oa-website.html",
      filename: "blog-line-oa-website.html",
      chunks: ["blog-line-oa-website"],
      scriptLoading: "defer",
    }),
    new HtmlWebpackPlugin({
      template: "./src/blog-responsive-design.html",
      filename: "blog-responsive-design.html",
      chunks: ["blog-responsive-design"],
      scriptLoading: "defer",
    }),
    new HtmlWebpackPlugin({
      template: "./src/blog-website-cost.html",
      filename: "blog-website-cost.html",
      chunks: ["blog-website-cost"],
      scriptLoading: "defer",
    }),
    new HtmlWebpackPlugin({
      template: "./src/blog-shopify-vs-custom.html",
      filename: "blog-shopify-vs-custom.html",
      chunks: ["blog-shopify-vs-custom"],
      scriptLoading: "defer",
    }),
    new HtmlWebpackPlugin({
      template: "./src/blog-page-speed.html",
      filename: "blog-page-speed.html",
      chunks: ["blog-page-speed"],
      scriptLoading: "defer",
    }),
    new HtmlWebpackPlugin({
      template: "./src/blog-landing-page.html",
      filename: "blog-landing-page.html",
      chunks: ["blog-landing-page"],
      scriptLoading: "defer",
    }),
    new HtmlWebpackPlugin({
      template: "./src/blog-ssl-https.html",
      filename: "blog-ssl-https.html",
      chunks: ["blog-ssl-https"],
      scriptLoading: "defer",
    }),
    new HtmlWebpackPlugin({
      template: "./src/blog-domain-hosting.html",
      filename: "blog-domain-hosting.html",
      chunks: ["blog-domain-hosting"],
      scriptLoading: "defer",
    }),
    new HtmlWebpackPlugin({
      template: "./src/blog-restaurant-website.html",
      filename: "blog-restaurant-website.html",
      chunks: ["blog-restaurant-website"],
      scriptLoading: "defer",
    }),
    new HtmlWebpackPlugin({
      template: "./src/blog-web-app-vs-mobile-app.html",
      filename: "blog-web-app-vs-mobile-app.html",
      chunks: ["blog-web-app-vs-mobile-app"],
      scriptLoading: "defer",
    }),
    new HtmlWebpackPlugin({
      template: "./src/blog-google-ads-website.html",
      filename: "blog-google-ads-website.html",
      chunks: ["blog-google-ads-website"],
      scriptLoading: "defer",
    }),
    new HtmlWebpackPlugin({
      template: "./src/blog-online-booking.html",
      filename: "blog-online-booking.html",
      chunks: ["blog-online-booking"],
      scriptLoading: "defer",
    }),
    new HtmlWebpackPlugin({
      template: "./src/blog-website-analytics.html",
      filename: "blog-website-analytics.html",
      chunks: ["blog-website-analytics"],
      scriptLoading: "defer",
    }),
    new HtmlWebpackPlugin({
      template: "./src/blog-website-copywriting.html",
      filename: "blog-website-copywriting.html",
      chunks: ["blog-website-copywriting"],
      scriptLoading: "defer",
    }),
    new HtmlWebpackPlugin({
      template: "./src/blog-clinic-website.html",
      filename: "blog-clinic-website.html",
      chunks: ["blog-clinic-website"],
      scriptLoading: "defer",
    }),
    new HtmlWebpackPlugin({
      template: "./src/blog-thai-ecommerce-tips.html",
      filename: "blog-thai-ecommerce-tips.html",
      chunks: ["blog-thai-ecommerce-tips"],
      scriptLoading: "defer",
    }),
    new HtmlWebpackPlugin({
      template: "./src/blog-pdpa-website.html",
      filename: "blog-pdpa-website.html",
      chunks: ["blog-pdpa-website"],
      scriptLoading: "defer",
    }),
    new HtmlWebpackPlugin({
      template: "./src/blog-website-maintenance.html",
      filename: "blog-website-maintenance.html",
      chunks: ["blog-website-maintenance"],
      scriptLoading: "defer",
    }),
    new HtmlWebpackPlugin({
      template: "./src/portfolio-luxe-watch.html",
      filename: "portfolio-luxe-watch.html",
      chunks: ["portfolio-luxe-watch"],
      scriptLoading: "defer",
    }),
    new HtmlWebpackPlugin({
      template: "./src/portfolio-cafe.html",
      filename: "portfolio-cafe.html",
      chunks: ["portfolio-cafe"],
      scriptLoading: "defer",
    }),
    new HtmlWebpackPlugin({
      template: "./src/portfolio-puphub.html",
      filename: "portfolio-puphub.html",
      chunks: ["portfolio-puphub"],
      scriptLoading: "defer",
    }),
    new HtmlWebpackPlugin({
      template: "./src/portfolio-glostar.html",
      filename: "portfolio-glostar.html",
      chunks: ["portfolio-glostar"],
      scriptLoading: "defer",
    }),
    new HtmlWebpackPlugin({
      template: "./src/portfolio-photographer.html",
      filename: "portfolio-photographer.html",
      chunks: ["portfolio-photographer"],
      scriptLoading: "defer",
    }),
    new CopyWebpackPlugin({
      patterns: [
        { from: "src/assets", to: "assets" },
        { from: "src/CNAME", to: "CNAME", toType: "file" },
      ],
    }),
  ],
};
